apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3                  #No of instances of pods for our application
  selector:
    matchLabels:
      app: nginy
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: shubham315/nginx-image-demo:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: demo
